# docker-compose.yml

services:
  back_end:
    build: .
    image: lucasdias79931/agssa
    command: python3 app.py
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads       # 👈 volume compartilhado
      - ./results:/app/results       # 👈 volume compartilhado
      - db-data:/etc/data
    depends_on:
      - rabbitmq
      - celery

  rabbitmq:
    image: docker.io/library/rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - rabbitmq
    volumes:
      - ./uploads:/app/uploads       # 👈 volume compartilhado
      - ./results:/app/results       # 👈 volume compartilhado
      - db-data:/etc/data

volumes:
  db-data:
