version: "3.8"

services:
  back_end:
    build: .
    image: lucas/agssa
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - db-data:/etc/data
    depends_on:
      - rabbitmq
      - celery

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5673"
      - "15673:15673"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - rabbitmq
    volumes:
      - db-data:/etc/data

volumes:
  db-data:
