events {}

http {
    upstream backend {
        server back_end:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /static/ {
            alias /app/aplicacao/static/;
        }
    }
}
